### ISSUE TITLE
PostCSS 5.2 compatibility

### ISSUE THREAD

**Issue by mrmlnc** [shellscape/postcss-less#60]
This package does not work with PostCSS 5.2 😿

**Comment by evilebottnawi** [comment]
@webschik we have some issue with new version, need your help

**Comment by Gaya** [comment]
Just stumbled upon this issue after browsing through a lot of issues with webpack loaders. Seems like PostCSS 5.2 broke mixins in `postcss-less` throwing "Unknown word" around.

**Comment by evilebottnawi** [comment]
@webschik ping

**Comment by webschik** [comment]
Very sorry, guys :( I don't have much time now, would be appreciated for PR and help! I will try to find the time next days and resolve the last important issues.

**Comment by wuvluv** [comment]
What was the last version of PostCSS that is stable with this syntax?

**Comment by evilebottnawi** [comment]
@wuvluv latest published in npm

**Comment by wuvluv** [comment]
@evilebottnawi Oh okay. I was thinking that this issue was related to the issue I've been having which is Mixins are broken and returning "Unknown word". Unfortunately for me, I had never utilized this _before_ it was seemingly broken in 5.2 according to this issue report so I am unaware if it was ever working with Mixins to begin with.

`.mixin {
	color: red;
}

.test {
	.mixin;
}`

Sorry if this is the wrong area to report this. It seems related, though.

**Comment by webschik** [comment]
@wuvluv, the version 0.14.0

**Comment by shellscape** [comment]
#65 was merged. I'm going to close this for now, but if there are any other issues with 5.2 that arise, please post a comment.
